
import type { Product } from './types';

// NOTE: The 'images' field now expects an array of full URLs.
// For mock data, we are using Unsplash URLs directly. In a real scenario,
// these would be URLs from your Firebase Storage.

export const sampleProducts: Product[] = [
  {
    id: 'p001',
    name: 'Vintage Floral Midi Dress',
    price: 1500.00,
    description: 'A beautiful vintage midi dress with a delicate floral pattern. Perfect for sunny afternoons. Features a button-up front and a tie waist.',
    category: 'Dresses',
    condition: 'Vintage',
    size: 'M',
    color: 'Cream',
    images: ['https://images.unsplash.com/photo-1503408024948-0a3e1b2b519c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw2fHxmbG9yYWwlMjBkcmVzc3xlbnwwfHx8fDE3NTk2MDk1OTR8MA&ixlib=rb-4.1.0&q=80&w=1080'],
    isFeatured: true,
    isSold: false,
    createdAt: new Date('2023-10-01T12:00:00Z'),
  },
  {
    id: 'p002',
    name: 'Classic Denim Jacket',
    price: 2500.00,
    description: 'A timeless Levi\'s denim jacket in a medium wash. An essential wardrobe staple that goes with everything. Broken in for a comfortable fit.',
    category: 'Outerwear',
    condition: 'Gently Used',
    size: 'L',
    color: 'Blue',
    images: ['https://images.unsplash.com/photo-1495105787522-5334e3ffa0ef?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwzfHxkZW5pbSUyMGphY2tldHxlbnwwfHx8fDE3NTk1ODg1ODZ8MA&ixlib=rb-4.1.0&q=80&w=1080'],
    isFeatured: true,
    isSold: false,
    createdAt: new Date('2023-10-02T12:00:00Z'),
  },
  {
    id: 'p003',
    name: 'High-Waisted Mom Jeans',
    price: 1200.00,
    description: 'Comfortable and stylish high-waisted mom jeans in a light wash. Features a relaxed fit and tapered leg. 100% cotton.',
    category: 'Bottoms',
    condition: 'Gently Used',
    size: 'S',
    color: 'Light Blue',
    images: ['https://images.unsplash.com/photo-1584642520442-5c5fbe4e7427?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxtb20lMjBqZWFuc3xlbnwwfHx8fDE3NTk1ODk0MzJ8MA&ixlib=rb-4.1.0&q=80&w=1080'],
    isFeatured: false,
    isSold: false,
    createdAt: new Date('2023-10-03T12:00:00Z'),
  },
  {
    id: 'p004',
    name: 'Retro Band T-Shirt',
    price: 800.00,
    description: 'A soft, worn-in graphic tee featuring a retro band logo. Perfect for a casual, edgy look. Single stitch, made in the USA.',
    category: 'Tops',
    condition: 'Vintage',
    size: 'M',
    color: 'Black',
    images: ['https://images.unsplash.com/photo-1621446511130-0ed6519bfeb6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwzfHxncmFwaGljJTIwdGVlfGVufDB8fHx8MTc1OTY4NzgxN3ww&ixlib=rb-4.1.0&q=80&w=1080'],
    isFeatured: false,
    isSold: true,
    createdAt: new Date('2023-09-28T12:00:00Z'),
  },
  {
    id: 'p005',
    name: 'Leather Crossbody Bag',
    price: 2000.00,
    description: 'A high-quality brown leather crossbody bag with brass hardware. Features multiple compartments and an adjustable strap. Minimal signs of wear.',
    category: 'Accessories',
    condition: 'Like New',
    size: 'One Size',
    color: 'Brown',
    images: ['https://images.unsplash.com/photo-1535120927584-0230f40fc1e2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw5fHxsZWF0aGVyJTIwYmFnfGVufDB8fHx8MTc1OTY0NDQwMHww&ixlib=rb-4.1.0&q=80&w=1080'],
    isFeatured: true,
    isSold: false,
    createdAt: new Date('2023-10-05T12:00:00Z'),
  },
  {
    id: 'p006',
    name: 'Oversized Knit Sweater',
    price: 1800.00,
    description: 'A cozy, oversized chunky knit sweater in a warm cream color. Made from a soft wool blend. Ideal for layering in cooler weather.',
    category: 'Tops',
    condition: 'Like New',
    size: 'L',
    color: 'Cream',
    images: ['https://images.unsplash.com/photo-1652904871839-2f815f42cb00?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw3fHxrbml0JTIwc3dlYXRlcnxlbnwwfHx8fDE3NTk1NjkxMDR8MA&ixlib=rb-4.1.0&q=80&w=1080'],
    isFeatured: false,
    isSold: false,
    createdAt: new Date('2023-10-04T12:00:00Z'),
  },
  {
    id: 'p007',
    name: 'Tortoise Shell Sunglasses',
    price: 750.00,
    description: 'Stylish vintage-inspired sunglasses with classic tortoise shell frames and UV400 protection lenses.',
    category: 'Accessories',
    condition: 'Like New',
    size: 'One Size',
    color: 'Brown',
    images: ['https://images.unsplash.com/photo-1584036553516-bf83210aa16c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw2fHxzdW5nbGFzc2VzfGVufDB8fHx8MTc1OTY1NDk4Nnww&ixlib=rb-4.1.0&q=80&w=1080'],
    isFeatured: false,
    isSold: false,
    createdAt: new Date('2023-09-30T12:00:00Z'),
  },
  {
    id: 'p008',
    name: 'Bohemian Maxi Skirt',
    price: 1300.00,
    description: 'A flowy, lightweight maxi skirt with a vibrant bohemian print. Features an elastic waistband for a comfortable fit.',
    category: 'Bottoms',
    condition: 'Gently Used',
    size: 'M',
    color: 'Multi-color',
    images: ['https://images.unsplash.com/photo-1649566650740-cb0a625e1b40?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw5fHxtYXhpJTIwc2tpcnR8ZW58MHx8fHwxNzU5Njg2Njk4fDA&ixlib=rb-4.1.0&q=80&w=1080'],
    isFeatured: false,
    isSold: false,
    createdAt: new Date('2023-09-29T12:00:00Z'),
  },
  {
    id: 'p009',
    name: 'Classic Plaid Flannel Shirt',
    price: 1000.00,
    description: 'A soft and durable plaid flannel shirt in a red and black pattern. Can be worn as a shirt or an overshirt.',
    category: 'Tops',
    condition: 'Gently Used',
    size: 'L',
    color: 'Red',
    images: ['https://images.unsplash.com/photo-1758506088339-505469f4463c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw2fHxwbGFpZCUyMHNoaXJ0fGVufDB8fHx8MTc1OTU4NzU4M3ww&ixlib=rb-4.1.0&q=80&w=1080'],
    isFeatured: true,
    isSold: false,
    createdAt: new Date('2023-09-25T12:00:00Z'),
  },
  {
    id: 'p010',
    name: 'Corduroy Mini Skirt',
    price: 900.00,
    description: 'A-line mini skirt made from soft black corduroy. A versatile piece for any season. Features a front zipper closure.',
    category: 'Bottoms',
    condition: 'Like New',
    size: 'S',
    color: 'Black',
    images: ['https://images.unsplash.com/photo-1527332042004-0b1a4d8646a3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxjb3JkdXJveSUyMHNraXJ0fGVufDB8fHx8MTc1OTY4NzgxOHww&ixlib=rb-4.1.0&q=80&w=1080'],
    isFeatured: false,
    isSold: true,
    createdAt: new Date('2023-09-22T12:00:00Z'),
  },
  {
    id: 'p011',
    name: 'Doc Martens Boots',
    price: 3000.00,
    description: 'Iconic Doc Martens 1460 boots in black leather. Perfectly broken-in with a lifetime of wear left. Some scuffs add to the character.',
    category: 'Accessories',
    condition: 'Vintage',
    size: 'L', // Corresponds to shoe size, simplified here
    color: 'Black',
    images: ['https://images.unsplash.com/photo-1602250523361-ff299f086e1e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw1fHxsZWF0aGVyJTIwYm9vdHN8ZW58MHx8fHwxNzU5NjY0MzA4fDA&ixlib=rb-4.1.0&q=80&w=1080'],
    isFeatured: false,
    isSold: false,
    createdAt: new Date('2023-09-20T12:00:00Z'),
  },
  {
    id: 'p012',
    name: 'Abstract Silk Scarf',
    price: 650.00,
    description: 'A beautiful 100% silk scarf with a colorful abstract pattern. Can be worn as a neck scarf, head wrap, or bag accessory.',
    category: 'Accessories',
    condition: 'Vintage',
    size: 'One Size',
    color: 'Multi-color',
    images: ['https://images.unsplash.com/photo-1517472292914-9570a594783b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwzfHxzaWxrJTIwc2NhcmZ8ZW58MHx8fHwxNzU5NjU2MDUwfDA&ixlib=rb-4.1.0&q=80&w=1080'],
    isFeatured: false,
    isSold: false,
    createdAt: new Date('2023-09-18T12:00:00Z'),
  },
];
