import type { Product } from './types';

export const sampleProducts: Product[] = [
  {
    id: 'p001',
    name: 'Vintage Floral Midi Dress',
    price: 45.00,
    description: 'A beautiful vintage midi dress with a delicate floral pattern. Perfect for sunny afternoons. Features a button-up front and a tie waist.',
    category: 'Dresses',
    condition: 'Vintage',
    size: 'M',
    color: 'Cream',
    images: ['p001_1', 'p001_2', 'p001_3'],
    isFeatured: true,
    isSold: false,
    createdAt: new Date('2023-10-01T12:00:00Z'),
  },
  {
    id: 'p002',
    name: 'Classic Denim Jacket',
    price: 60.00,
    description: 'A timeless Levi\'s denim jacket in a medium wash. An essential wardrobe staple that goes with everything. Broken in for a comfortable fit.',
    category: 'Outerwear',
    condition: 'Gently Used',
    size: 'L',
    color: 'Blue',
    images: ['p002_1', 'p002_2'],
    isFeatured: true,
    isSold: false,
    createdAt: new Date('2023-10-02T12:00:00Z'),
  },
  {
    id: 'p003',
    name: 'High-Waisted Mom Jeans',
    price: 35.00,
    description: 'Comfortable and stylish high-waisted mom jeans in a light wash. Features a relaxed fit and tapered leg. 100% cotton.',
    category: 'Bottoms',
    condition: 'Gently Used',
    size: 'S',
    color: 'Light Blue',
    images: ['p003_1'],
    isFeatured: false,
    isSold: false,
    createdAt: new Date('2023-10-03T12:00:00Z'),
  },
  {
    id: 'p004',
    name: 'Retro Band T-Shirt',
    price: 25.00,
    description: 'A soft, worn-in graphic tee featuring a retro band logo. Perfect for a casual, edgy look. Single stitch, made in the USA.',
    category: 'Tops',
    condition: 'Vintage',
    size: 'M',
    color: 'Black',
    images: ['p004_1'],
    isFeatured: false,
    isSold: true,
    createdAt: new Date('2023-09-28T12:00:00Z'),
  },
  {
    id: 'p005',
    name: 'Leather Crossbody Bag',
    price: 55.00,
    description: 'A high-quality brown leather crossbody bag with brass hardware. Features multiple compartments and an adjustable strap. Minimal signs of wear.',
    category: 'Accessories',
    condition: 'Like New',
    size: 'One Size',
    color: 'Brown',
    images: ['p005_1'],
    isFeatured: true,
    isSold: false,
    createdAt: new Date('2023-10-05T12:00:00Z'),
  },
  {
    id: 'p006',
    name: 'Oversized Knit Sweater',
    price: 40.00,
    description: 'A cozy, oversized chunky knit sweater in a warm cream color. Made from a soft wool blend. Ideal for layering in cooler weather.',
    category: 'Tops',
    condition: 'Like New',
    size: 'L',
    color: 'Cream',
    images: ['p006_1'],
    isFeatured: false,
    isSold: false,
    createdAt: new Date('2023-10-04T12:00:00Z'),
  },
  {
    id: 'p007',
    name: 'Tortoise Shell Sunglasses',
    price: 28.00,
    description: 'Stylish vintage-inspired sunglasses with classic tortoise shell frames and UV400 protection lenses.',
    category: 'Accessories',
    condition: 'Like New',
    size: 'One Size',
    color: 'Brown',
    images: ['p007_1'],
    isFeatured: false,
    isSold: false,
    createdAt: new Date('2023-09-30T12:00:00Z'),
  },
  {
    id: 'p008',
    name: 'Bohemian Maxi Skirt',
    price: 38.00,
    description: 'A flowy, lightweight maxi skirt with a vibrant bohemian print. Features an elastic waistband for a comfortable fit.',
    category: 'Bottoms',
    condition: 'Gently Used',
    size: 'M',
    color: 'Multi-color',
    images: ['p008_1'],
    isFeatured: false,
    isSold: false,
    createdAt: new Date('2023-09-29T12:00:00Z'),
  },
  {
    id: 'p009',
    name: 'Classic Plaid Flannel Shirt',
    price: 32.00,
    description: 'A soft and durable plaid flannel shirt in a red and black pattern. Can be worn as a shirt or an overshirt.',
    category: 'Tops',
    condition: 'Gently Used',
    size: 'L',
    color: 'Red',
    images: ['p009_1'],
    isFeatured: true,
    isSold: false,
    createdAt: new Date('2023-09-25T12:00:00Z'),
  },
  {
    id: 'p010',
    name: 'Corduroy Mini Skirt',
    price: 30.00,
    description: 'A-line mini skirt made from soft black corduroy. A versatile piece for any season. Features a front zipper closure.',
    category: 'Bottoms',
    condition: 'Like New',
    size: 'S',
    color: 'Black',
    images: ['p010_1'],
    isFeatured: false,
    isSold: true,
    createdAt: new Date('2023-09-22T12:00:00Z'),
  },
  {
    id: 'p011',
    name: 'Doc Martens Boots',
    price: 95.00,
    description: 'Iconic Doc Martens 1460 boots in black leather. Perfectly broken-in with a lifetime of wear left. Some scuffs add to the character.',
    category: 'Accessories',
    condition: 'Vintage',
    size: 'L', // Corresponds to shoe size, simplified here
    color: 'Black',
    images: ['p011_1'],
    isFeatured: false,
    isSold: false,
    createdAt: new Date('2023-09-20T12:00:00Z'),
  },
  {
    id: 'p012',
    name: 'Abstract Silk Scarf',
    price: 22.00,
    description: 'A beautiful 100% silk scarf with a colorful abstract pattern. Can be worn as a neck scarf, head wrap, or bag accessory.',
    category: 'Accessories',
    condition: 'Vintage',
    size: 'One Size',
    color: 'Multi-color',
    images: ['p012_1'],
    isFeatured: false,
    isSold: false,
    createdAt: new Date('2023-09-18T12:00:00Z'),
  },
];
